export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAILURE = "GET_QUESTIONS_FAILURE";

export const SET_USER_QUESTION = "SET_USER_QUESTION";
export const FILTER_QUESTIONS = "FILTER_QUESTIONS";

export const SET_SELECTED_QUESTION = "SET_SELECTED_QUESTION";

export const SUBMIT_NEW_QUESTION_REQUEST = "SUBMIT_NEW_QUESTION_REQUEST";
export const SUBMIT_NEW_QUESTION_SUCCESS = "SUBMIT_NEW_QUESTION_SUCCESS";
export const SUBMIT_NEW_QUESTION_FAILURE = "SUBMIT_NEW_QUESTION_FAILURE";
